### ISSUE TITLE
Error: Enyim.Caching.Memcached.MemcachedException: object too large for cache

### ISSUE THREAD

**Issue by Pahanbl4** [vieapps/Enyim.Caching#5]
Enyim.Caching.Memcached.MemcachedException: object too large for cache    at Enyim.Caching.Memcached.PooledSocket.ReadResponse()

How can i increase the cache values?

**Comment by quynh-ng** [comment]
Hi,

By default, the memcached server accepts max-size of ONE item is 1MB.

So, you can re-set the configuration of your memcached server to accept more than 1MB, and you can search StackOverflow for that configuratioon (ex: https://stackoverflow.com/questions/4795536/increase-item-max-size-in-memcached)

The second ways to prevent this issue its use SetAsFragment method instead of Set method.

**Comment by Pahanbl4** [comment]
@quynh-ng thank you very much)
